version: '3.8'
services:
  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=12345
    ports:
      - "1433:1433"

  seq:
    image: datalust/seq:latest
    container_name: ecommerce-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true   
    ports:
      - "5341:80"   # UI
      - "5342:5341" # ingestion (opsiyonel)
